language: node_js
node_js:
  - "6"
  - "6.1"
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run test
notifications:
  slack: fullstack101:q9OW3lRUYS1gxCtzsmGFthtt
